# Generated by Django 5.0.14 on 2026-08-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
                ('started_at', models.DateField()),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RotationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='e.g. PySpark Session, Code Review, Public Speaking', max_length=150)),
                ('rotation_type', models.CharField(choices=[('DAILY', 'Daily'), ('EVERY_2_DAYS', 'Every 2 Days'), ('WEEKLY', 'Weekly'), ('CUSTOM_CYCLIC', 'Custom Cyclic Allocation')], default='DAILY', max_length=20)),
                ('custom_pattern_json', models.CharField(default='[1]', help_text='JSON array for custom daily presenter allocations e.g. [1, 4, 2]', max_length=255)),
                ('presenters_per_day', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('skip_weekends', models.BooleanField(default=True)),
                ('skip_holidays', models.BooleanField(default=True)),
                ('current_cycle', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='media/presentations/')),
                ('notes', models.TextField(blank=True, default='')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rotation.presentationcycle')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='presentationcycle',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='rotation.rotationconfig'),
        ),
        migrations.CreateModel(
            name='MissedPresenterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_presentations', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotation.rotationconfig')),
            ],
        ),
    ]
