# Generated by Django 5.0.14 on 2026-08-09 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationcycle',
            name='config',
        ),
        migrations.AlterModelOptions(
            name='presentationschedule',
            options={'ordering': ['scheduled_date', 'start_time']},
        ),
        migrations.RenameField(
            model_name='presentationcycle',
            old_name='completed_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='presentationschedule',
            old_name='completed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='presentationschedule',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='presentationcycle',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='presentationschedule',
            name='presentation_file',
        ),
        migrations.AddField(
            model_name='presentationcycle',
            name='activity',
            field=models.CharField(default='Code Review', max_length=100),
        ),
        migrations.AddField(
            model_name='presentationcycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentationcycle',
            name='name',
            field=models.CharField(default='Code Review - Cycle 1', max_length=150),
        ),
        migrations.AddField(
            model_name='presentationcycle',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='activity',
            field=models.CharField(default='Code Review', max_length=100),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='end_time',
            field=models.TimeField(default='11:00:00'),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='reference_material',
            field=models.FileField(blank=True, null=True, upload_to='media/presentation_refs/'),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='start_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='presentationschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='presentationschedule',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('REMINDER_SENT', 'Reminder Sent'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=25),
        ),
        migrations.CreateModel(
            name='PresentationReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_actions', to=settings.AUTH_USER_MODEL)),
                ('new_presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_presentations', to=settings.AUTH_USER_MODEL)),
                ('old_presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_presentations', to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='rotation.presentationschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/presentations/')),
                ('file_name', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='rotation.presentationschedule')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MissedPresenterQueue',
        ),
        migrations.DeleteModel(
            name='RotationConfig',
        ),
    ]
