# Generated by Django 5.0.14 on 2026-08-10 15:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_leaderboard', '0002_remove_presentationfeedback_presentation'),
        ('rotation', '0003_wheel_session_result_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationschedule',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='presentationreschedule',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='presentationreschedule',
            name='new_presenter',
        ),
        migrations.RemoveField(
            model_name='presentationreschedule',
            name='old_presenter',
        ),
        migrations.RemoveField(
            model_name='presentationreschedule',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='presentationschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='presentationschedule',
            name='presenter',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='wheelsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wheelspinresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='CodeExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, default='', max_length=255)),
                ('explanation_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_explanations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='rotation.reviewcycle')),
            ],
            options={
                'ordering': ['-explanation_date', '-created_at'],
                'unique_together': {('cycle', 'member')},
            },
        ),
        migrations.DeleteModel(
            name='PresentationCycle',
        ),
        migrations.DeleteModel(
            name='PresentationReschedule',
        ),
        migrations.DeleteModel(
            name='PresentationSchedule',
        ),
        migrations.DeleteModel(
            name='PresentationSubmission',
        ),
    ]
