# Generated by Django 5.0.14 on 2026-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_company_user_is_email_verified_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TECHNICAL', 'Technical Support'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
