databases:
  - name: tracksprint-db
    databaseName: tracksprint
    user: tracksprint_user

services:
  # Backend Web Service
  - type: web
    name: tracksprint-backend
    env: python
    region: frankfurt
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn --chdir backend config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: tracksprint-db
          property: connectionString
      - key: AWS_STORAGE_BUCKET_NAME
        value: agilisium-task-portal-evidence
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_REGION_NAME
        value: eu-north-1

  # Frontend Static Site
  - type: web
    name: tracksprint-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
