# Generated by Django 5.0.14 on 2026-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_format',
            field=models.CharField(choices=[('PPT', 'PPT Presentation (.ppt, .pptx)'), ('DOC', 'Word Document (.doc, .docx)'), ('IMAGE', 'Image Format (.png, .jpg, .jpeg)'), ('ANY', 'Any Format')], default='ANY', max_length=20),
        ),
    ]
