# Generated by Django 5.0.14 on 2026-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_allowed_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allowed_format',
            field=models.CharField(choices=[('PPT', 'PPT Presentation (.ppt, .pptx)'), ('DOC', 'Word Document (.doc, .docx)'), ('IMAGE', 'Image Format (.png, .jpg, .jpeg)'), ('PDF', 'PDF Document (.pdf)'), ('ANY', 'Any Format')], default='ANY', max_length=20),
        ),
    ]
