# Generated by Django 5.0.14 on 2026-08-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationfeedback',
            name='presentation',
        ),
    ]
