# Generated by Django 5.0.14 on 2026-08-10 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_leaderboard', '0002_remove_presentationfeedback_presentation'),
        ('rotation', '0004_remove_presentationschedule_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationfeedback',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='rotation.codeexplanation'),
        ),
    ]
